# Stage 1: Build the Angular app
FROM node:14 as build

WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire Angular project to the container
COPY . .

# Build the Angular app for production
RUN npm run build

# Stage 2: Serve the Angular app
FROM nginx:alpine

# Copy the built Angular app from the previous stage to the nginx web root
COPY --from=build /app/dist/ /usr/share/nginx/html

# Expose port 80 (the default HTTP port)
EXPOSE 80

# Start the nginx web server
CMD ["nginx", "-g", "daemon off;"]
